# The Mod TOML file for Ceilands.

modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# License Schmicense
license="MIT"

[[mods]] #mandatory
	modId="ceilands"
	version="${version}"
	displayName="The Ceilands"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/the-ceilands" 
	issueTrackerURL="https://github.com/Kitteh6660/Ceilands/issues"
	logoFile="logo.png" #optional
	authors="Kitteh6660" #optional
	
	credits="Thank you /u/Raphe9000 for the wonderful idea! Thank you firenh#7567 for the textures!" #optional
	
	# The description text for the mod (multi line!) (#mandatory)
	description='''The Ceilands is a mod that adds the titular dimension with bedrock ceiling but no bedrock floor!'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ceilands]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1.3,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ceilands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceilands]]
    modId="blueprint"
    mandatory=false
    versionRange="[1.20.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ceilands]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.20.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ceilands]]
    modId="twilightforest"
    mandatory=false
    versionRange="[4.3.1893,)"
    ordering="AFTER"
    side="BOTH"